# Tensorflow

In [2]:
import tensorflow as tf

print('TensorFlow', tf.__version__)

2026-04-20 07:43:29.369679: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow 2.20.0


In [3]:
import numpy as np

x = np.linspace(0, 1, 5)
print(x)
print(type(x), x.shape, x.dtype)

[0.   0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'> (5,) float64


In [5]:
import tensorflow as tf

x = tf.linspace(0, 1, 5)
print(x)
print(type(x), x.shape, x.dtype)

tf.Tensor([0.   0.25 0.5  0.75 1.  ], shape=(5,), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'> (5,) <dtype: 'float64'>


In [13]:
x = list(range(12))
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [7]:
x = np.arange(12)
print(x)
x = x.reshape(3, 4)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
x = tf.range(12)
print(x)
# x = x.reshape((3, 4)) # TensorFlow에서는 reshape이 아니라 tf.reshape 함수를 사용해야 합니다.
x = tf.reshape(x, shape=(3, 4))
print(x)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)
